spring:
  application:
    name: easymensa-backend
  datasource:
    username: root
    password: IiN49z4p8
    url: jdbc:mariadb://localhost:3306/easymensa?useUnicode=true&characterEncoding=UTF-8
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: validate

    open-in-view: true
    properties:
      hibernate: org.hibernate.dialect.MariaDB10Dialect
  flyway:
    enabled: true
    schemas:
      - easymensa
    default-schema: easymensa
    locations: ['classpath:db/migration']
    create-schemas: true
    user: root
    password: IiN49z4p8
    url: jdbc:mariadb://localhost:3306



