spring:
  application:
    name: easymensa-backend
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/easymensa
    username: root
    password: 2024

  flyway:
    enabled: true
    schemas:
      - easymensa
    create-schemas: true
    url: jdbc:mariadb://localhost:3306
    user: root
    password: 2024

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      dialect: org.hibernate.dialect.MariaDBDialect


