server:
  port: 5000
spring:
  application:
    name: easymensa-backend
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:easymensa
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      dialect: org.hibernate.dialect.H2Dialect


