INSERT INTO allergen (name, description, short_name) VALUES ('Gluten', 'Gluten ist eine Gruppe von Proteinen, die in bestimmten Getreidesorten wie Weizen, Gerste und Roggen vorkommen.', 'GLUT');
INSERT INTO allergen (name, description, short_name) VALUES ('Krustentiere', 'Krustentiere umfassen verschiedene Arten von Meeresfrüchten wie Garnelen, Krabben und Hummer.', 'KRUS');
INSERT INTO allergen (name, description, short_name) VALUES ('Eier', 'Eier sind ein häufiges Allergen, das in vielen Gerichten und Produkten vorkommt.', 'EIER');
INSERT INTO allergen (name, description, short_name) VALUES ('Fisch', 'Fischallergie ist eine der häufigsten Lebensmittelallergien.', 'FISH');
INSERT INTO allergen (name, description, short_name) VALUES ('Erdnüsse', 'Erdnussallergie ist eine der schwersten Lebensmittelallergien.', 'PEAN');
INSERT INTO allergen (name, description, short_name) VALUES ('Sojabohnen', 'Sojabohnen sind eine häufige Zutat in vielen verarbeiteten Lebensmitteln.', 'SOJA');
INSERT INTO allergen (name, description, short_name) VALUES ('Milch', 'Milchallergie ist bei Säuglingen und kleinen Kindern häufig.', 'MILCH');
INSERT INTO allergen (name, description, short_name) VALUES ('Nüsse', 'Nüsse wie Mandeln, Walnüsse und Cashewnüsse sind häufige Allergene.', 'NÜSSE');
INSERT INTO allergen (name, description, short_name) VALUES ('Sellerie', 'Sellerie ist eine häufige Zutat in Suppen, Salaten und Eintöpfen.', 'SELL');
INSERT INTO allergen (name, description, short_name) VALUES ('Senf', 'Senfallergie kann milde bis schwere Reaktionen verursachen.', 'SEN');