name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Install zip
        run: apt-get update && apt-get install -y zip

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Unit Tests
        run: mvn test --file pom.xml

      - name: Create deployment package
        run: |
          zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: easymensa
          environment_name: Easymensa-dev
          version_label: "v$(date +'%Y%m%d%H%M%S')"
          region: eu-west-1
          deployment_package: deploy.zip
