name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mvn_result=$?
          if [ $mvn_result -ne 0 ]; then
            echo "Maven build failed with exit code $mvn_result"
            exit $mvn_result
          fi

      - name: Run Unit Tests
        run: mvn test --file pom.xml

      - name: Create deployment package
        run: |
          mv target/easymensa-backend-0.0.1-SNAPSHOT.jar
          if [ ! -f "deploy-4.jar" ]; then
            echo "Failed to create deployment package."
            exit 1
          fi

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: easymensa
          environment_name: Easymensa-env
          version_label: easymensa-version-4
          region: eu-west-3
          deployment_package: deploy-4.jar
