name: Continuous Integration
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          mvn_result=$?
          if [ $mvn_result -ne 0 ]; then
            echo "Maven build failed with exit code $mvn_result"
            exit $mvn_result
          fi

      - name: Run Unit Tests
        run: mvn test --file pom.xml

      - name: Create deployment package and version label
        run: |
          # Get the current commit's SHA
          commit_sha=${{ github.sha }}

          # Construct dynamic version and filename
          dynamic_version="easymensa-version-${commit_sha}"
          deployment_zip="${dynamic_version}.zip"

          # Create deployment package with dynamic filename
          zip -r "$deployment_zip" . -x '*.git*'

          # Check if the zip file was created successfully
          if [ ! -f "$deployment_zip" ]; then
            echo "Failed to create deployment package."
            exit 1
          fi

          # Set dynamic version environment variable
          echo "DYNAMIC_VERSION=$dynamic_version" >> $GITHUB_ENV

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: easymensa
          environment_name: Easymensa-env
          version_label: ${{ env.DYNAMIC_VERSION }}  # Use environment variable
          region: eu-west-3
          use_existing_version_if_available: true
          deployment_package: "$deployment_zip"